/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prova01;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorio
 */
public class InterfaceCadastro extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceCadastro.class.getName());

    /**
     * Creates new form InterfaceCadastro
     */

    public InterfaceCadastro() {
        initComponents();
        
        Arquivo.carregarTabela(tblLivros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpTipo = new javax.swing.ButtonGroup();
        btnGprStatus = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        rdoFisico = new javax.swing.JRadioButton();
        rdoDigital = new javax.swing.JRadioButton();
        txtAno = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox<>();
        rdoNaoIniciado = new javax.swing.JRadioButton();
        rdoEmAndamento = new javax.swing.JRadioButton();
        rdoConcluido = new javax.swing.JRadioButton();
        pnlLivros = new javax.swing.JScrollPane();
        tblLivros = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CADASTRO DE LIVROS");

        jLabel2.setText("Título:");

        jLabel3.setText("Tipo:");

        jLabel4.setText("Autor:");

        jLabel5.setText("Ano de publicação:");

        jLabel7.setText("Categoria:");

        jLabel8.setText("Status:");

        btnGrpTipo.add(rdoFisico);
        rdoFisico.setText("Físico");

        btnGrpTipo.add(rdoDigital);
        rdoDigital.setText("Digital");
        rdoDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDigitalActionPerformed(evt);
            }
        });

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnologia", "Ficção", "Romance", "História" }));

        btnGprStatus.add(rdoNaoIniciado);
        rdoNaoIniciado.setText("Não iniciado");

        btnGprStatus.add(rdoEmAndamento);
        rdoEmAndamento.setText("Em andamento");

        btnGprStatus.add(rdoConcluido);
        rdoConcluido.setText("Concluído");

        tblLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TITULO", "AUTOR", "ANO PUB.", "CATEGORIA", "TIPO", "STATUS"
            }
        ));
        pnlLivros.setViewportView(tblLivros);

        btnCadastrar.setText("CASDASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(pnlLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdoFisico)
                                    .addGap(27, 27, 27)
                                    .addComponent(rdoDigital))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdoNaoIniciado)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoEmAndamento)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoConcluido))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnEditar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCadastrar))))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoFisico)
                    .addComponent(rdoDigital)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNaoIniciado)
                    .addComponent(rdoEmAndamento)
                    .addComponent(rdoConcluido)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addComponent(pnlLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDigitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoDigitalActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String titulo = txtTitulo.getText();
        String autor = txtAutor.getText();
        String anoPublicacao = txtAno.getText();
        String categoria = ""+cmbCategoria.getSelectedItem();
        String tipo = " ";
        String status = " ";

        if (rdoDigital.isSelected() == true) {
            tipo = "Digital";
        } else if (rdoFisico.isSelected() == true) {
            tipo = "Fisico";
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o tipo!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
        if (rdoConcluido.isSelected() == true) {
            status = "Concluido";
        } else if (rdoEmAndamento.isSelected() == true) {
            status = "Em andamento";
        } else if (rdoNaoIniciado.isSelected() == true) {
            status = "Nao iniciado";
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o status!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
        DefaultTableModel tabela = (DefaultTableModel) tblLivros.getModel();
        
        tabela.addRow(new Object[] {
            titulo, autor, anoPublicacao, categoria, tipo, status});
        
        Arquivo.salvar(titulo, autor, anoPublicacao, tipo, categoria, status);

        txtTitulo.setText("");
        txtAutor.setText("");
        txtAno.setText("");
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linha = tblLivros.getSelectedRow();
        
        if (linha == -1) {
             JOptionPane.showMessageDialog(this, "Selecione um livro na tabela!");
             return;
        }
        String titulo = txtTitulo.getText();
        String autor = txtAutor.getText();
        String anoPublicacao = txtAno.getText();
        String categoria = ""+cmbCategoria.getSelectedItem();
        String tipo = " ";
        String status = " ";

        if (rdoDigital.isSelected() == true) {
            tipo = "Digital";
        } else if (rdoFisico.isSelected() == true) {
            tipo = "Fisico";
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o tipo!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
        if (rdoConcluido.isSelected() == true) {
            status = "Concluido";
        } else if (rdoEmAndamento.isSelected() == true) {
            status = "Em andamento";
        } else if (rdoNaoIniciado.isSelected() == true) {
            status = "Nao iniciado";
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o status!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
        tblLivros.setValueAt(titulo, linha, 0);
        tblLivros.setValueAt(autor, linha, 1);
        tblLivros.setValueAt(anoPublicacao, linha, 2);
        tblLivros.setValueAt(categoria, linha, 3);
        tblLivros.setValueAt(tipo, linha, 4);
        tblLivros.setValueAt(status, linha, 5);
        
        JOptionPane.showMessageDialog(this, "Livro editado");

        Arquivo.salvarTabela(tblLivros);
        
        txtTitulo.setText("");
        txtAutor.setText("");
        txtAno.setText("");
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfaceCadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.ButtonGroup btnGprStatus;
    private javax.swing.ButtonGroup btnGrpTipo;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane pnlLivros;
    private javax.swing.JRadioButton rdoConcluido;
    private javax.swing.JRadioButton rdoDigital;
    private javax.swing.JRadioButton rdoEmAndamento;
    private javax.swing.JRadioButton rdoFisico;
    private javax.swing.JRadioButton rdoNaoIniciado;
    private javax.swing.JTable tblLivros;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
